In [3]:
import numpy as np

In [2]:
arr=np.array([1,34,56])

In [3]:
arr

array([ 1, 34, 56])

In [4]:
arr2=np.array([[1,34,56],[90,67,78]])

In [5]:
arr2

array([[ 1, 34, 56],
       [90, 67, 78]])

In [6]:
arr.ndim

1

In [7]:
arr2.ndim

2

In [12]:
arr3=np.array([[[1,34,56],[90,67,78],[56,78,45]]])

In [13]:
arr3.ndim

3

In [15]:
arr[2]

56

In [19]:
arr2[1]

array([90, 67, 78])

In [20]:
arr[0:2]

array([ 1, 34])

In [21]:
arr2[0,2]

56

In [22]:
arr2

array([[ 1, 34, 56],
       [90, 67, 78]])

In [23]:
arr3

array([[[ 1, 34, 56],
        [90, 67, 78],
        [56, 78, 45]]])

In [31]:
arr3[0,1,2]

78

In [29]:
arr3

array([[[ 1, 34, 56],
        [90, 67, 78],
        [56, 78, 45]]])

In [33]:
arr3[0,1,1:]

array([67, 78])

In [4]:
temperature_data = [25.3, 26.1, 24.8, 23.5, 27.2]
pressure_data = [101.2, 100.8, 101.5, 100.2, 101.0]
humidity_data = [55.2, 54.8, 56.5, 53.7, 55.9]

In [5]:
data=np.concatenate((temperature_data,pressure_data,humidity_data))

In [6]:
# Create a numpy array of this dataset

In [7]:
temperature_array = np.array(temperature_data)

pressure_array = np.array(pressure_data)

humidity_array = np.array(humidity_data)

In [8]:
# Calculate the mean of each quantity

In [10]:
temperature_mean = np.mean(temperature_array)
pressure_mean = np.mean(pressure_array)
humidity_mean = np.mean(humidity_array)
print(temperature_mean,pressure_mean,humidity_mean)

25.380000000000003 100.94 55.21999999999999


In [11]:
# Calculate the Standard Deviation

In [12]:
np.std(temperature_array)

1.2416118556135003

In [13]:
np.std(temperature_array)

 

np.std(pressure_array)

 

np.std(humidity_array)

0.9579144011862429

In [14]:
# Calculate min and max values

In [15]:
print(f"""Temperature: {np.max(temperature_array)} {np.min(temperature_array)}
Pressure: {np.max(pressure_array)} {np.min(pressure_array)}
Humidity: {np.max(humidity_array)} {np.min(humidity_array)}""")

Temperature: 27.2 23.5
Pressure: 101.5 100.2
Humidity: 56.5 53.7
